### ISSUE TITLE
Common template framework for Directx 11 and 12

### ISSUE THREAD

**Issue by mediabuff** [walbourn/directx-vs-templates#10]
It will be great if we could have common plumbing and app can be developed for DX11 with easy path to DX12. Right now the API models seem to be very different.

Similarly, a common 'static lib' approach for both win32 and uwp.

**Comment by walbourn** [comment]
Supporting both DirectX 11 and DirectX 12 in the same application/game is a quite complex undertaking as it require a lot of abstraction. The purpose of these templates is to focus on learning DirectX rather than trying to be a 'game engine'. If you really need a robust solution that can target both, you should look at an established engine like Unreal or Unity.

I often use these templates with _DirectX Tool Kit_ as well, which for similar reasons is an "either/or" choice for [DirectX 11](https://github.com/Microsoft/DirectXTK) vs. [DirectX 12](https://github.com/Microsoft/DirectXTK12).

That said, I make a point of using the same coding pattern where possible to minimize the mental friction moving between them.

**Comment by mediabuff** [comment]
thank you.
