### ISSUE TITLE
Retire the 'non-DR' variant of the template

### ISSUE THREAD

**Issue by walbourn** [walbourn/directx-vs-templates#17]
For a while I've been maintaining two different variants of every template: One that creates the device 'inline' (``CreateDevice`` and ``CreateResources``), and the other with the ``DeviceResources`` abstraction (``CreateDeviceDependentResources``, ``CreateWindowSizeDependentResources``).

Generally the non-DR variants are only really useful when doing extremely simple samples, primarily focused on the creation of the device & swapchain itself. Otherwise, you pretty much always want to use the DR variant. Plus the ``DeviceResources`` version is a lot more functional.

As such, I think I'm going to retire the non-DR versions primarily to reduce the work to maintain these things... (6 templates instead of 12)

**Comment by walbourn** [comment]
Note I'll also need to revisit the _DirectX Tool Kit_ for DX 11 / DX12 tutorials to make them all use the DeviceResources version of the template...

**Comment by aaronstackpole** [comment]
Interestingly, for the latest iteration of my platform code I actually started from the non-DR template because I encapsulated and abstracted the device resources differently than you did. I ended up encapsulating the factory/device/context in a separate object from the swap chain and buffers, it was easier to start from the simpler version because then I didn't have to untangle any of the callbacks to do what I wanted. The non-DR templates are not entirely useless.

**Comment by walbourn** [comment]
I have updated the *DirectX Tool Kit* tutorials to use the DR variant for all lessons except the first one.

**Comment by aaronstackpole** [comment]
Yikes, going to have to update my podcast plan, lol, had been doing a short series making a set of 2D games, but I had been using the non-DR variant to follow along with the tutorials. Thanks for the heads up, at least I have a couple days to review before the next show!

**Comment by aaronstackpole** [comment]
The main thing I did was got rid of all pointer passing in the template, instead I just built a simple service registry that would make unique_ptr objects for other classes and retain a pointer to the object that it makes. Then, in any other object that needs a pointer, I just go and get it from the service registry. My main objective actually was just to detangle the game class from doing everything, each of the many things the game class was doing is now separated out into its own object (a class for managing the window, a class for the rendering pipeline objects, a class for loading content, a class for handling game state, another for game tick pumping, etc.) Basically, I took that frankenstein's monster of a game class you have here as an example and turned it into a much more mature and robust application of my own. As with most Microsoft examples, the intent is not to provide production ready code, but to provide samples of how the API works so that you can write a good application to your own standards. As someone who's worked with Microsoft technology since I was eight... DOS 2.2... I have always appreciated the work being done by all of you!
