### ISSUE TITLE
Please provide VS2017 directx-vs-templates

### ISSUE THREAD

**Issue by sdcb** [walbourn/directx-vs-templates#4]

**Comment by walbourn** [comment]
I plan to as soon as VS 2017 is final.

**Comment by Zingam** [comment]
Is there any reason why these templates are not included in VS or available from the "Find online" feature. At least I couldn't find them.

It would be nice if they also are put into a separate group like "DirectX" in VS under "Templates->Visual C++ -> Windows" as we already have ATL, CLR, MFC, Cross Platform etc. At least that was what I was expecting to find after I installed them. Because I couldn't see such group, I thought that the installation failed.

**Comment by walbourn** [comment]
The latest release of the [Direct3DUWPGame](https://github.com/walbourn/directx-vs-templates/releases/tag/mar2017b) VSIX now supports both VS 2015 and VS 2017.
