### ISSUE TITLE
win32 app - blank white screen when resizing

### ISSUE THREAD

**Issue by mediabuff** [walbourn/directx-vs-templates#9]
Hi - I don't get the cornflower background when the screen is resized - to blanks out to white during resizing.

**Comment by walbourn** [comment]
With the Creators Update (15086) or later when built with the Windows 10 SDK (15086) or later, the UWP template uses the ``ResizeStarted`` and ``ResizeCompleted`` handlers to avoid doing swapchain resizes over and over again as the window is resized. If you don't like that behavior, you can disable the registration of these handlers.

Also, check the ``swapChainDesc.Scaling`` value you are using. In the latest templates it should be ``DXGI_SCALING_ASPECT_RATIO_STRETCH``, but ``DXGI_SCALING_STRETCH`` should also work. Maybe you are using ``DXGI_SCALING_NONE``?

**Comment by mediabuff** [comment]
Sorry, I take it back. The problem is in Win32. UWP works fine. The scaling used is DXGI_SCALING_STRETCH. I just created a fresh project using the template.

**Comment by walbourn** [comment]
What OS are you using?

**Comment by mediabuff** [comment]
Win10, Version 1709 (OS Build 16299.15). It didn't work in earlier builds of Win10 as well.

**Comment by mediabuff** [comment]
Any update?

**Comment by walbourn** [comment]
So I've tracked down the issue here. Basically in normal operation I only render when there is "idle time" in the message loop rather than ``WM_PAINT``. The specific case of being in the ``WM_ENTER_SIZE`` case, however, prevents any 'idle' processing so nothing gets drawn. The fix here is to replace ``WM_PAINT`` in ``Main.cpp`` with:

    case WM_PAINT:
        if (s_in_sizemove)
        {
            game->Tick();
        }
        break;

That said, I'm not sure if that's the fully 100% robust solution, but it seems to resolve this concern.

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/walbourn/directx-vs-templates/commit/c03bf5a6d0f03d1eed3b8f360aa0afb76bc8dc90). Will update the VSIX later today...
